apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextjs-prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextjs-prometheus
  template:
    metadata:
      labels:
        app: nextjs-prometheus
    spec:
      containers:
        - name: nextjs-prometheus
          image: nextjs-prometheus:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: nextjs-prometheus
spec:
  selector:
    app: nextjs-prometheus
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP