apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s
    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']
      - job_name: "demo-job"
        metrics_path: "/api/metrics"
        static_configs:
          - targets: ["nextjs-prometheus:3000"]